#!/bin/bash
#
# Author: Riley Shott (https://github.com/Ginja/Admin_Scripts)
#
# margarita        Startup script for the maragita webinterface
#
# chkconfig: 356 90 20
# description: Margarita is a web front-end to reposado
# the Apple Software Update replication and
# catalog management tool.
#
# Forked by Alex Markessinis (https://github.com/MelonSmasher)
# 
# This script has been modified to work with specific settings.
#
# It also assumes that there is a user called reposync that owns the reposync files.
 
# Source function library
. /etc/rc.d/init.d/functions
 
# Variables
PID=$(ps aux | grep 'sudo -u reposync [p]ython /usr/local/src/margarita/margarita.py -p 5000 -b 127.0.0.1' | awk '{print $2}')
RETVAL=0
 
# Methods
start()
{
 echo -n "Starting margarita: "
 if [ -z $PID ]; then
  sudo -u reposync python /usr/local/src/margarita/margarita.py -p 5000 -b 127.0.0.1 &> /var/log/margarita.log &
  RETVAL=$?
  if [ $RETVAL -eq 0 ]
    then success
    else failure
  fi
  echo
  return $RETVAL
 else
  failure
  RETVAL=1
  echo "Margarita already running: "
  return $RETVAL
 fi
}
 
stop()
{
 echo -n "Stopping margarita: "
 if [ $PID ]; then
  kill $PID
 RETVAL=$?
  if [ $RETVAL -eq 0 ]
    then success
    else failure
  fi
  PID=""
  echo
  return $RETVAL
 else
  failure
  RETVAL=1
  echo "Margarita wasn't running: "
  return $RETVAL
 fi
}

restart () {
  stop
  start
}

status()
{
  if [ $PID ]; then
    echo "Margarita is running"
  exit 0

  else
  echo "Margarita isn't running"
    exit 1
  fi
}

usage () {
  echo $"Usage: $0 {start|stop|restart|status|usage}"
}
 
# Punch it
case "$1" in
start)
  start;;
stop)
  stop;;
restart)
  restart;;
status)
  status;;
usage)
  usage;;
*)
  usage
  exit 1
esac
 
exit $RETVAL